'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {getCatalog,getEntry} from '@/lib/content/client';
import {useHarfStore} from '@/lib/data/store';
import {saveNote,setPaused,prioritizeEntry} from '@/lib/learning/commands';
import {clearNoteDraft,readNoteDraft,writeNoteDraft} from '@/lib/data/note-draft';
import {RootFamily} from '@/components/reader/RootFamily';
import {familiarity} from '@/lib/learning/scheduler';
import {ResourceMessage,useResource} from './useResource';
export function WordDetail({id}:{id:string}){const load=useCallback(()=>getEntry(id),[id]),resource=useResource(load),catalog=useResource(getCatalog),store=useHarfStore();const stored=store.notes.find(n=>n.id===id)?.text??'';const [draft,setDraft]=useState<string|null>(null),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const text=draft??stored;const dirty=text!==stored;
 useEffect(()=>{setDraft(readNoteDraft(id));},[id]);
 useEffect(()=>{if(!dirty)return;const guard=(e:BeforeUnloadEvent)=>{e.preventDefault();};const click=(e:MouseEvent)=>{const link=(e.target as HTMLElement).closest('a');if(link&&link.getAttribute('href')&&!window.confirm('Leave without saving your note?'))e.preventDefault();};window.addEventListener('beforeunload',guard);document.addEventListener('click',click,true);return()=>{window.removeEventListener('beforeunload',guard);document.removeEventListener('click',click,true);};},[dirty]);
 async function act(fn:()=>Promise<unknown>,message:string){setBusy(true);setError('');try{await fn();setMessage(message);}catch(e){setError(e instanceof Error?e.message:'Could not save. Try again.');}finally{setBusy(false);}}
 if(!resource.data)return <ResourceMessage {...resource}/>;const {entry,examples}=resource.data;const card=store.cards.find(c=>c.id===`vocabulary:${id}`);const family=catalog.data?.entries.filter(e=>entry.root&&e.root===entry.root&&e.id!==id)??[];
 return <div className="stack"><Link href="/learn">← Vocabulary</Link><header className="page-header"><p className="eyebrow">{familiarity(card)} · {entry.occurrenceCount.toLocaleString()} occurrences</p><h1 className="study-word arabic-text" lang="ar" dir="rtl">{entry.arabic}</h1><p className="translation">{entry.gloss}</p><p className="muted">{entry.transliteration}</p></header><div className="row"><button className="button button-primary" disabled={busy||store.status!=='ready'||!!card?.paused} onClick={()=>void act(()=>prioritizeEntry(id),'Added to your next new-word queue. Daily limits still apply.')}>Study next</button>{card&&<button className="button button-secondary" disabled={busy||store.status!=='ready'} onClick={()=>void act(()=>setPaused('vocabulary',id,!card.paused),card.paused?'Reviews resumed.':'Reviews paused.')}>{card.paused?'Resume reviews':'Pause reviews'}</button>}{card&&<span className="muted">Next review: {new Date(card.card.due).toLocaleString()}</span>}</div>{message&&<p role="status">{message}</p>}{error&&<p role="alert">{error}</p>}<section className="stack"><h2>In context</h2>{examples.map(example=><article className="sheet stack" key={example.targetKey}><Link href={`/read/${example.ref.replace(':','/')}?word=${example.targetKey.split(':')[2]}`}>Ayah {example.ref}</Link><p className="quran-text" dir="rtl" lang="ar">{example.tokens.map(t=><span key={t.key} className={t.key===example.targetKey?'selected-token':''}>{t.arabic}{' '}</span>)}</p><p><strong>{example.targetGloss}</strong> — meaning at this position</p><p className="translation">{example.translation}</p></article>)}</section>{entry.root&&<section className="stack"><h2>Related root</h2><p className="arabic-text" dir="rtl" lang="ar">{entry.root}</p><p className="muted">Related words can have different meanings. Studying one does not mark the others familiar.</p>{entry.rootId&&<RootFamily id={entry.rootId}/>}<h3>Related entries in this course</h3>{family.map(e=><Link href={`/learn/${e.id}`} key={e.id}><span lang="ar" dir="rtl">{e.arabic}</span> · {e.gloss}</Link>)}</section>}<section className="stack"><h2>Your memory note</h2><label className="field">A personal reminder<textarea rows={4} maxLength={1000} value={text} onChange={e=>{setDraft(e.target.value);writeNoteDraft(id,e.target.value);}}/></label><small>{text.length} / 1,000 characters{dirty?' · Unsaved changes':''}</small><button className="button button-primary" disabled={!dirty||busy||store.status!=='ready'} onClick={()=>void act(async()=>{await saveNote(id,text);clearNoteDraft(id);setDraft(null);},'Note saved.')}>Save note</button></section><Link href="/sources">Content sources and review status</Link></div>;
}
