'use client';
import { useState, type FormEvent } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useHarfStore } from '@/lib/data/store';
import { updateSettings } from '@/lib/learning/commands';
import { startCourse } from '@/components/learning/start';
import { Button, StatusMessage } from '@/components/ui';
export default function StartPage(){const router=useRouter();const store=useHarfStore();const[dailyNew,setDailyNew]=useState<3|5|10>(5);const[transliteration,setTransliteration]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');async function submit(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError('');try{await updateSettings({dailyNew,introTransliteration:transliteration,onboardingComplete:true});const session=await startCourse();router.push(`/study?session=${encodeURIComponent(session.id)}`);}catch(cause){setError(cause instanceof Error?cause.message:'Your preferences could not be saved. Try again.');}finally{setBusy(false);}}return <div className="setup"><p className="eyebrow">Your first few words</p><h1>Make room for a few words.</h1><p className="muted">You can already read Arabic script; this course focuses on meaning.</p><form className="stack" onSubmit={submit}><fieldset disabled={busy}><legend>New vocabulary entries per day</legend><div className="choice-options">{([3,5,10] as const).map(number=><label key={number} className="choice"><input type="radio" name="dailyNew" value={number} checked={dailyNew===number} onChange={()=>setDailyNew(number)}/>{number}</label>)}</div></fieldset><label className="choice"><input type="checkbox" checked={transliteration} disabled={busy} onChange={event=>setTransliteration(event.target.checked)}/>Show transliteration when introducing a new word</label><p>We’ll begin with up to three words. You can change your daily allowance at any time.</p><p className="muted">Guest progress stays in this browser; signed-in progress also syncs. You can export a backup in Settings.</p>{store.status==='unavailable'&&<StatusMessage error>{store.error} You can still <Link href="/read">explore the Quran</Link>.</StatusMessage>}{error&&<StatusMessage error>{error}</StatusMessage>}<Button type="submit" disabled={busy||store.status!=='ready'}>{busy?'Preparing your session…':store.status==='loading'?'Opening progress storage…':'Start my first session'}</Button><Link href="/read">Explore first</Link></form></div>;}
