'use client';
import { Suspense } from 'react';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { getCatalog } from '@/lib/content/client';
import { useHarfStore } from '@/lib/data/store';
import { familiarity } from '@/lib/learning/scheduler';
import { ResourceMessage, useResource } from '@/components/learning/useResource';
function Browser() {
    const catalog = useResource(getCatalog), store = useHarfStore(), params = useSearchParams(), router = useRouter(); const q = params.get('q') ?? '', status = params.get('status') ?? 'All', sort = params.get('sort') ?? 'course', due = params.get('due') === '1';
    function change(key: string, value: string) { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); if (key !== 'page') next.delete('page'); router.replace(`/learn?${next}`, { scroll: false }); }
    if (!catalog.data) return <ResourceMessage {...catalog} />;
    const now = Date.now(); const records = new Map(store.cards.filter(c => c.collection === 'vocabulary').map(c => [c.entryId, c])); const normalize = (s: string) => s.normalize('NFD').replace(/\p{M}/gu, '').toLocaleLowerCase();
    const rows = catalog.data.entries.filter(e => { const c = records.get(e.id); return (status === 'All' || familiarity(c) === status) && (!due || c && !c.paused && Date.parse(c.card.due) <= now) && normalize(`${e.arabic} ${e.lemma} ${e.root ?? ''} ${e.gloss} ${e.transliteration}`).includes(normalize(q)); }).sort((a, b) => sort === 'frequency' ? b.occurrenceCount - a.occurrenceCount : sort === 'alphabetical' ? a.transliteration.localeCompare(b.transliteration) : a.courseOrder - b.courseOrder);
    const page = Math.min(Math.max(1, Number(params.get('page')) || 1), Math.max(1, Math.ceil(rows.length / 30)));
    return <div className="stack"><header className="page-header"><p className="eyebrow">Vocabulary, in context</p><h1>Learn</h1><p>Explore {catalog.data.entries.length} frequent vocabulary entries.</p></header>{params.get('notice') && <div className="status-message row"><p>{params.get('notice') === 'legacy-entry' ? 'This older root entry has no verified equivalent in the new vocabulary course. Its progress is preserved in your legacy archive.' : 'This activity has been retired. Its saved progress is preserved in your legacy archive.'}</p><button className="button button-secondary" onClick={() => change('notice', '')}>Dismiss</button></div>}<div className="filters"><label className="field">Search vocabulary<input value={q} onChange={e => change('q', e.target.value)} maxLength={200} placeholder="Arabic, meaning, or transliteration" /></label><label className="field">Status<select value={status} onChange={e => change('status', e.target.value)}>{['All', 'New', 'Learning', 'Familiar', 'Paused'].map(s => <option key={s}>{s}</option>)}</select></label><label className="field">Sort<select value={sort} onChange={e => change('sort', e.target.value)}><option value="course">Course order</option><option value="frequency">Frequency</option><option value="alphabetical">Alphabetical</option></select></label><label className="choice"><input type="checkbox" checked={due} onChange={e => change('due', e.target.checked ? '1' : '')} />Due now</label></div><p role="status" className="muted">{rows.length} entries</p><ul className="entry-list">{rows.slice((page - 1) * 30, page * 30).map(e => <li key={e.id}><Link className="list-row entry-link" href={`/learn/${e.id}`}><span><span className="entry-arabic" lang="ar" dir="rtl">{e.arabic}</span><span className="entry-gloss">{e.gloss}</span><small className="muted">{e.transliteration} · {e.occurrenceCount.toLocaleString()} occurrences</small></span><span className="badge">{store.status === 'loading' ? '…' : familiarity(records.get(e.id))}</span></Link></li>)}</ul>{!rows.length && <p>No entries match. Clear a filter or try a different word.</p>}<nav className="row between" aria-label="Vocabulary pages"><button className="button button-secondary" disabled={page <= 1} onClick={() => change('page', String(page - 1))}>Previous</button><span>Page {page} of {Math.max(1, Math.ceil(rows.length / 30))}</span><button className="button button-secondary" disabled={page * 30 >= rows.length} onClick={() => change('page', String(page + 1))}>Next</button></nav><Link href="/collections/names">Explore the Names of Allah collection →</Link></div>;
}
export default function Learn() { return <Suspense fallback={<p>Opening vocabulary…</p>}><Browser /></Suspense>; }
