'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { getNames } from '@/lib/content/client';
import { useResource, ResourceMessage } from '@/components/learning/useResource';
import { startCourse } from '@/components/learning/start';
import { useHarfStore } from '@/lib/data/store';
import { familiarity } from '@/lib/learning/scheduler';
import { ArabicText, Button, StatusMessage } from '@/components/ui';
export default function NamesPage(){const names=useResource(getNames);const store=useHarfStore();const router=useRouter();const[query,setQuery]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const records=new Map(store.cards.filter(c=>c.collection==='names').map(c=>[c.entryId,c]));const due=[...records.values()].filter(c=>!c.paused&&Date.parse(c.card.due)<=Date.now()).length;
 async function start(){if(busy)return;setBusy(true);setError('');try{const session=await startCourse('names');router.push(`/study?session=${encodeURIComponent(session.id)}`);}catch(cause){setError(cause instanceof Error?cause.message:'The session could not start. Please retry.');}finally{setBusy(false);}}
 if(!names.data)return <ResourceMessage error={names.error} retry={names.retry}/>;const needle=query.trim().normalize('NFKC').toLocaleLowerCase();const filtered=names.data.filter(name=>`${name.id} ${name.arabic} ${name.transliteration} ${name.meaning}`.normalize('NFKC').toLocaleLowerCase().includes(needle));const unverified=names.data.some(name=>!name.verified);
 return <div className="stack"><header className="page-header"><p className="eyebrow">An optional collection</p><h1>The Names of Allah</h1><p>Practice recognizing the Names and their recorded meanings. This collection has its own review schedule and does not contribute to Quran vocabulary overlap.</p></header>{unverified&&<StatusMessage>This personal collection uses the original Harf Names, meanings and explanations you selected. <Link href="/sources">Read about this collection</Link>.</StatusMessage>}<section className="sheet stack"><h2>{store.status==='loading'?'Opening your reviews…':`${due} Names ready to review`}</h2><p>Introduce up to {store.settings.namesDailyNew} new Names per day. Change this allowance in <Link href="/settings">Settings</Link>.</p>{store.activeSession&&store.activeSession.collection!=='names'?<p>A vocabulary session is already in progress. <Link href={`/study?session=${encodeURIComponent(store.activeSession.id)}`}>Finish or end it before starting Names.</Link></p>:<Button disabled={busy||store.status!=='ready'} onClick={()=>void start()}>{busy?'Preparing…':store.activeSession?'Resume Names':'Study Names'}</Button>}{store.status==='unavailable'&&<StatusMessage error>{store.error}</StatusMessage>}{error&&<StatusMessage error>{error}</StatusMessage>}</section><label className="field">Search Names<input type="search" maxLength={200} value={query} onChange={event=>setQuery(event.target.value)} placeholder="Name, number, or meaning"/></label><p role="status" className="muted">{filtered.length} Names</p><ol className="names-list">{filtered.map(name=><li key={name.id}><details><summary><span className="muted">{name.id}.</span><ArabicText className="entry-arabic">{name.arabic}</ArabicText><span>{name.transliteration}</span><span className="badge">{store.status==='loading'?'…':familiarity(records.get(String(name.id)))}</span></summary><div className="stack names-detail"><h2>{name.meaning}</h2>{name.explanation&&<p>{name.explanation}</p>}<p className="muted">{name.root&&<>Root: {name.root} · </>}{name.verified?'Source and editorial review verified':'Original personal collection'}: {name.sourceIds.join(', ')||'Legacy Harf Names dataset'}.</p><Link href="/sources">Source details</Link></div></details></li>)}</ol>{!filtered.length&&<p>No Names match. Try another spelling or meaning.</p>}<Link href="/learn">Back to vocabulary</Link></div>;
}
