import Link from 'next/link';
import { readAyah } from '@/lib/content/server';
import { Wordmark } from '@/components/shell/AppShell';
import { LandingActions } from '@/components/shell/LandingActions';
import { LandingDemo } from '@/components/shell/LandingDemo';
export default async function LandingPage(){
 const ayah=await readAyah('1:2');
 const example=ayah?.tokens.find(token=>token.key==='1:2:3');
 if(!example)throw Error('The introduction example is missing from the content package.');
 return <><a href="#main-content" className="skip-link">Skip to content</a><header className="landing-header"><Wordmark/><Link href="/today" className="button button-text">Open Harf</Link></header><main id="main-content" className="landing-main" tabIndex={-1}><div className="landing-hero"><section><p className="eyebrow" style={{marginBottom:16}}>Quranic Arabic, a few words at a time</p><h1 className="landing-title">Meet familiar words in every ayah.</h1><p className="landing-copy">Learn Quranic vocabulary through short reviews, then see the words in context.</p><LandingActions/></section><LandingDemo arabic={example.arabic} gloss={example.gloss}/></div><section className="landing-steps" aria-label="How Harf works"><div><span className="eyebrow">01</span><h2>Learn a word</h2><p className="muted">Begin with a small number of frequent words and their meanings in an ayah.</p></div><div><span className="eyebrow">02</span><h2>Recall its meaning</h2><p className="muted">Try to remember, reveal the answer, and choose when you need to see it again.</p></div><div><span className="eyebrow">03</span><h2>Read it in context</h2><p className="muted">Return to the Quran and notice the vocabulary becoming familiar.</p></div></section><section><h2>Your learning, on your device.</h2><p className="muted" style={{marginTop:12}}>No account is needed for guest study. Sign in from Profile to sync progress across devices, or export a backup from Settings. Your first sign-in starts fresh.</p></section><footer className="landing-footer"><p className="muted">Vocabulary familiarity is a beginning, not a measure of understanding the Quran.</p><Link href="/sources">Sources and methodology</Link></footer></main></>;
}
