import Link from 'next/link';
import sources from '@/data/sources.json';
import {readCatalog} from '@/lib/content/server';

export default async function Sources(){
 const catalog=await readCatalog();
 return <div className="stack">
  <header className="page-header"><p className="eyebrow">Know what you are learning</p><h1>Sources and methodology</h1><p>Harf keeps source, permission, and editorial status visible instead of treating generated content as automatically approved.</p></header>
  {!catalog.releaseReady&&<section className="status-message stack"><h2>Local review build — not approved for publication</h2><p>This personal build is usable without publication approval. The records below distinguish your source choices from independent review and documented reuse permissions.</p><ul>{catalog.blockers.map(blocker=><li key={blocker}>{blocker}</li>)}</ul></section>}
  <section className="stack"><h2>Pinned content sources</h2><p>Arabic word positions, contextual glosses, transliteration, lemmas, roots, and the Hilali/Khan translation come from pinned Quranic Universal Library exports. Translation is an interpretation of meaning; word glosses depend on their position and context.</p><div className="table-scroll"><table><caption className="sr-only">Pinned Harf content sources</caption><thead><tr><th scope="col">Resource</th><th scope="col">Retrieved</th><th scope="col">Permission</th></tr></thead><tbody>{sources.files.map(file=><tr key={file.path}><th scope="row">{file.url?<a href={file.url}>{file.sourceVersion}</a>:<span>{file.sourceVersion}</span>}<br/><small className="muted">{file.attribution}</small></th><td>{file.retrievedAt}</td><td>{file.permission}</td></tr>)}</tbody></table></div><a href="https://qul.tarteel.ai/">Quranic Universal Library ↗</a></section>
  <section className="stack"><h2>Grammar and root families</h2><p>Word parts and grammatical features come from the retained Quranic Arabic Corpus. Full root families use canonical QUL occurrences, with original QuranWBW explanatory notes and verb forms attached to their original examples. A root connects related words; it does not make their meanings interchangeable.</p><p>Three source phrases are split into two reader words. Their shared meaning, analysis and recording are labelled as a phrase. Word recordings use the filenames supplied by the retained Quran.com export on audio.qurancdn.com.</p><a href={`/content/${catalog.contentVersion}/source-notices.txt`}>Read the original Corpus source notice</a></section>
  <section className="stack"><h2>Commentary and Quran insights</h2><p>The restored English Ibn Kathir commentary is attributed to QUL resource 35 under QUL's published download-and-package permission. Surah summaries, topic labels, and similar-passage indexes remain derived study aids awaiting qualified editorial review.</p><p>Similarity scores describe repeated wording in this dataset. They do not claim that two ayahs have identical meanings or interpretations.</p><Link href="/insights">Explore Quran insights</Link></section>
  <section className="stack"><h2>Vocabulary familiarity</h2><p>Harf schedules retrieval practice using FSRS. A word is labeled Familiar after it reaches a review stability of at least 21 days. This describes a scheduling state, not proof of understanding.</p><p>Vocabulary overlap counts unique canonical Quran word positions assigned to Familiar course entries, divided by all canonical word positions. End markers are excluded and overlapping positions count once. No percentage measures understanding of an ayah or the Quran.</p></section>
  <section className="stack"><h2>Names of Allah</h2><p>This personal app uses the original Harf 99 Names, including their Arabic forms, pronunciation labels, meanings, roots and explanations, selected by the owner on 2 October 2026. NumroQ is no longer the active Names source. External publisher and independent editorial review are not recorded; this does not prevent personal study. Names scheduling and progress remain separate from vocabulary.</p></section>
  <section className="stack"><h2>Your data</h2><p>Guest progress stays in this browser. Optional accounts use Supabase for email sign-in and synchronization of progress, notes, bookmarks and study preferences. Each account has a separate browser cache; guest data is not imported. Theme preference stays local. There is no analytics tracking. Clearing site data removes guest progress and unsynced changes.</p><p>Supabase receives your email, synced records, and normal connection information when accounts are used. Audio and optional prayer times are requested from their named providers when used. Those providers receive the normal network information associated with the request.</p><p>Already-loaded study content can work after losing the network. Cold offline navigation shows an honest fallback instead of promising a complete offline Quran library.</p><Link href="/settings">Export your progress from Settings →</Link></section>
  <p className="muted">Content version: {catalog.contentVersion}</p>
 </div>;
}
