'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import {parseRef} from '@/lib/content/refs';
import {highlightRanges,splitHighlighted} from '@/lib/search/highlight';
import type {SearchMode} from '@/lib/content/schema';
export function QuranSearch(){const params=useSearchParams(),router=useRouter();const selected=params.get('mode')??'reference';const mode=['reference','arabic','english','transliteration'].includes(selected)?selected:'reference';const query=params.get('q')??'';const worker=useRef<Worker|null>(null),request=useRef(0);const [results,setResults]=useState<{ref:string;text:string}[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false),[revision,retry]=useState(0);
 useEffect(()=>()=>{request.current++;worker.current?.terminate();worker.current=null;},[]);
 useEffect(()=>{const id=++request.current;setResults([]);setError('');setLoading(false);const q=query.trim();if(!q)return;if(mode==='reference'){const ref=parseRef(q);if(ref)setResults([{ref:q,text:`Open ayah ${q}`}]);else setError('Enter a valid reference, such as 2:255.');return;}if(q.length<(mode==='arabic'?2:3))return;setLoading(true);const timer=setTimeout(()=>{try{worker.current??=new Worker(new URL('../../lib/workers/search.worker.ts',import.meta.url));worker.current.onmessage=e=>{if(e.data.id!==request.current)return;setLoading(false);setResults(e.data.results??[]);setError(e.data.error??'');};worker.current.onerror=()=>{if(id===request.current){setLoading(false);setError('Search could not start. Try again.');worker.current?.terminate();worker.current=null;}};worker.current.postMessage({id,mode:mode as SearchMode,query:q});}catch{setLoading(false);setError('Search is unavailable in this browser.');}},250);return()=>{clearTimeout(timer);request.current++;};},[query,mode,revision]);
 function update(key:string,value:string){request.current++;setResults([]);const next=new URLSearchParams(params);next.set(key,value);router.replace(`/read?${next}`,{scroll:false});}
 return <section className="stack" aria-label="Search the Quran"><div className="filters"><label className="field">Search by<select value={mode} onChange={e=>update('mode',e.target.value)}><option value="reference">Reference</option><option value="arabic">Arabic</option><option value="english">English</option><option value="transliteration">Transliteration</option></select></label><label className="field">{mode==='reference'?'Surah:ayah':'Search words'}<input type="search" maxLength={200} dir={mode==='arabic'?'rtl':'ltr'} lang={mode==='arabic'?'ar':'en'} value={query} onChange={e=>update('q',e.target.value)} placeholder={mode==='reference'?'2:255':mode==='arabic'?'الرحمن':'Enter words'}/></label></div>{error&&<div role="alert"><p>{error}</p>{mode!=='reference'&&<button className="button button-secondary" onClick={()=>retry(n=>n+1)}>Retry search</button>}</div>}{loading&&<p role="status">Searching…</p>}{query&&!loading&&!error&&<p role="status" className="muted">{results.length?`${results.length} results${results.length===30?' · first 30 matches':''}`:query.length<(mode==='arabic'?2:3)?'Enter more characters to search.':'No matches. Try another spelling or search mode.'}</p>}<ul className="entry-list">{results.map(r=>{const shown=r.text.slice(0,240);const segments=mode==='reference'?[{text:shown,match:false}]:splitHighlighted(shown,highlightRanges(shown,query,mode as SearchMode));return <li key={r.ref}><Link className="list-row search-result" href={`/read/${r.ref.replace(':','/')}`}><strong>{r.ref}</strong><span dir={mode==='arabic'?'rtl':'ltr'} lang={mode==='arabic'?'ar':'en'}>{segments.map((seg,i)=>seg.match?<mark key={i}>{seg.text}</mark>:<span key={i}>{seg.text}</span>)}{r.text.length>240?'…':''}</span></Link></li>;})}</ul></section>;
}
