'use client';
import Link from 'next/link';
import {useCallback,useEffect,useRef,useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import {getAyah} from '@/lib/content/client';
import {adjacentRef} from '@/lib/content/refs';
import {useHarfStore} from '@/lib/data/store';
import {setLastVerse,toggleBookmark} from '@/lib/learning/commands';
import {useResource,ResourceMessage} from '@/components/learning/useResource';
import {AudioControl} from './AudioControl';
import {stopAudio,verseAudioUrl} from '@/lib/audio';
import {Dialog} from '@/components/ui/Dialog';
import {TafsirPanel} from './TafsirPanel';
import {WordAnalysis} from './WordAnalysis';
export function Reader({reference}:{reference:string}){const load=useCallback(()=>getAyah(reference),[reference]),resource=useResource(load),store=useHarfStore(),params=useSearchParams(),router=useRouter();const [error,setError]=useState(''),[wide,setWide]=useState(false),[context,setContext]=useState(false);const article=useRef<HTMLElement>(null);const selected=Number(params.get('word'));const token=resource.data?.tokens.find(t=>t.position===selected&&t.kind==='word');
 useEffect(()=>{const media=matchMedia('(min-width:1200px)');const update=()=>setWide(media.matches);update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);
 useEffect(()=>{stopAudio();setContext(false);return()=>stopAudio();},[reference,store.settings.reciter]);
 useEffect(()=>{if(!resource.data||store.status!=='ready'||!article.current)return;let timer:ReturnType<typeof setTimeout>|undefined;let visible=false;const schedule=()=>{clearTimeout(timer);if(visible&&document.visibilityState==='visible')timer=setTimeout(()=>void setLastVerse(reference).catch(()=>{}),2000);};const observer=new IntersectionObserver(entries=>{visible=entries.some(e=>e.isIntersecting);schedule();});observer.observe(article.current);document.addEventListener('visibilitychange',schedule);return()=>{observer.disconnect();clearTimeout(timer);document.removeEventListener('visibilitychange',schedule);};},[resource.data,store.status,reference]);
 const close=()=>{const next=new URLSearchParams(params);next.delete('word');router.replace(`/read/${reference.replace(':','/')}?${next}`,{scroll:false});};
 if(!resource.data)return <ResourceMessage {...resource}/>;const ayah=resource.data;const prev=adjacentRef(reference,-1),next=adjacentRef(reference,1);const [s,a]=reference.split(':') as [string,string];const panel=token&&<div className="stack"><p className="study-word arabic-text" dir="rtl" lang="ar">{token.arabic}</p><h3>{token.gloss||'No word gloss available'}</h3><p>{token.transliteration}</p><WordAnalysis key={token.key} wordKey={token.key}/>{token.root&&<p>Root: <span className="arabic-text" dir="rtl" lang="ar">{token.root}</span></p>}{token.lemma&&<p>Lemma: <span className="arabic-text" dir="rtl" lang="ar">{token.lemma}</span></p>}{token.entryId?<Link href={`/learn/${token.entryId}`}>Explore this vocabulary entry →</Link>:<p className="muted">This word is outside the current vocabulary course.</p>}</div>;
 return <div className="stack"><header className="page-header"><Link href="/read">← All surahs</Link><h1>Ayah {reference}</h1></header><div className="reader-layout"><article ref={article} className="reader-verse stack"><div className="row"><AudioControl url={verseAudioUrl(s,a,store.settings.reciter)}/><button className="button button-secondary" disabled={store.status!=='ready'} aria-pressed={store.bookmarks.some(b=>b.id===reference)} onClick={()=>void toggleBookmark(reference).catch(e=>setError(e.message))}>{store.bookmarks.some(b=>b.id===reference)?'Remove bookmark':'Bookmark ayah'}</button></div>{error&&<p role="alert">{error}</p>}<p className="quran-text" dir="rtl" lang="ar" style={{fontSize:store.settings.arabicSize}}>{ayah.tokens.map(t=>t.kind==='end-marker'?<span key={t.key} aria-hidden="true">{t.arabic} </span>:<button key={t.key} className={`token-button ${token?.key===t.key?'selected-token':''}`} aria-label={`${t.arabic}, ${t.gloss}`} aria-pressed={token?.key===t.key} onClick={()=>router.replace(`/read/${s}/${a}?word=${t.position}`,{scroll:false})}>{t.arabic}</button>)}</p><p className="translation">{ayah.translation}</p><p className="muted">{ayah.translationSource}</p>{ayah.notes.length>0&&<details><summary>Footnotes ({ayah.notes.length})</summary><ol className="stack">{ayah.notes.map((n,i)=><li key={i}>{n.text}{n.ref&&<> <Link href={`/read/${n.ref.surah}/${n.ref.ayah}`}>See {n.ref.surah}:{n.ref.ayah} →</Link></>}</li>)}</ol></details>}<nav className="row between" aria-label="Ayah navigation">{prev?<Link className="button button-secondary" href={`/read/${prev.replace(':','/')}`}>← {prev}</Link>:<span>First ayah</span>}{next?<Link className="button button-secondary" href={`/read/${next.replace(':','/')}`}>{next} →</Link>:<span>Last ayah</span>}</nav><details onToggle={e=>setContext(e.currentTarget.open)}><summary>Read adjacent context</summary>{context&&<div className="stack">{prev&&<Context reference={prev}/>} {next&&<Context reference={next}/>}</div>}</details><div className="row"><Link href={`/insights/${s}/${a}`}>Themes and related passages →</Link></div><TafsirPanel key={reference} reference={reference}/></article>{wide&&<aside className="word-panel sheet stack" aria-label="Selected word">{token?<><div className="row between"><h2>Word meaning</h2><button className="button button-secondary" onClick={close}>Close</button></div>{panel}</>:<><h2>Explore a word</h2><p>Select an Arabic word to see its meaning and vocabulary entry.</p></>}</aside>}</div>{!wide&&<Dialog open={!!token} onClose={close} title="Word meaning">{panel}</Dialog>}</div>;
}
function Context({reference}:{reference:string}){const load=useCallback(()=>getAyah(reference),[reference]),resource=useResource(load);return !resource.data?<ResourceMessage {...resource}/>:<section className="stack"><Link href={`/read/${reference.replace(':','/')}`}>Ayah {reference}</Link><p className="quran-text" dir="rtl" lang="ar">{resource.data.tokens.map(t=>t.arabic).join(' ')}</p><p>{resource.data.translation}</p></section>;}
