'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useEffect, type ReactNode } from 'react';
import {useSyncStatus} from '@/lib/account/sync';
import { stopAudio } from '@/lib/audio';
const destinations = [{ href:'/today',label:'Today',path:'M3 10 12 3l9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z' },{href:'/learn',label:'Learn',path:'M4 3h7v18H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2Zm9 0h7a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-7'},{href:'/practice',label:'Practice',path:'m8 12 3 3 5-6m4-3v12a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h8'},{href:'/read',label:'Read',path:'M12 7c-3-3-7-3-10-2v15c3-1 7-1 10 2m0-15c3-3 7-3 10-2v15c-3-1-7-1-10 2V7'},{href:'/insights',label:'Insights',path:'M9 18h6m-5 3h4m-7-9a5 5 0 1 1 10 0c0 2-1 3-2 4H9c-1-1-2-2-2-4Z'},{href:'/progress',label:'Progress',path:'M4 20V10m8 10V4m8 16v-7'}];
export function SyncNotice(){const status=useSyncStatus();return status.kind==='error'||status.kind==='conflict'?<div role="status" className="status-message"><p>Progress is saved on this device, but cloud sync needs attention.</p><Link href="/profile">Review sync in Profile →</Link></div>:null;}
export function Wordmark(){ return <Link href="/" className="wordmark" aria-label="Harf home"><span lang="ar" dir="rtl">حرف</span> Harf</Link>; }
function Links({pathname,mobile=false}:{pathname:string;mobile?:boolean}) { return destinations.filter(item=>!mobile||item.href!=='/insights').map(item=><Link key={item.href} href={item.href} className="nav-link" aria-current={(pathname===item.href || pathname.startsWith(`${item.href}/`) || (item.href==='/learn' && pathname.startsWith('/collections'))) ? 'page':undefined}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={item.path}/></svg><span>{item.label}</span></Link>); }
export function AppShell({ children }: { children: ReactNode }) { const pathname=usePathname(); useEffect(()=>{stopAudio();},[pathname]); return <><a href="#main-content" className="skip-link">Skip to content</a><aside className="app-rail"><Wordmark/><nav aria-label="Main"><Links pathname={pathname}/></nav><div className="rail-footer"><Link href="/profile" className="settings-link">Profile</Link><Link href="/settings" className="settings-link">Settings</Link><Link href="/sources" className="settings-link">Sources</Link></div></aside><div className="app-body"><header className="mobile-header"><Wordmark/><Link className="settings-link" href="/profile">Profile</Link><Link className="settings-link" href="/settings">Settings</Link></header><main id="main-content" className="app-main" tabIndex={-1}><SyncNotice/>{children}</main></div><nav className="bottom-nav" aria-label="Main"><Links pathname={pathname} mobile/></nav></>; }
